[CartoonNetwork] Fixed AttributeError
* [CartoonNetwork] Changed cvp to ngtv

 Changed cvp to ngtv and also fixed AttributeError: 'NoneType' object has no attribute 'groups'

* Just removed some code that is not needed

* Removed none needed stuff

* Fixed cartoonnetwork not working with Adobe Pass

* [CartoonNetwork] Made it in the format of everything else.

* [CartoonNetwork] Changes stuff I forgot

Changed description's label from authType to description

* [CartoonNetwork] Fixed shortclips

ShortClips don't have descriptions, so it will crash but now it's fixed.

* [Cartoonnetwork] Allowing more support if the website changes.

* Fixed Adobe Pass thinking it's needs TV logins

* Now lets see if that fixed adobe pass.

* my my let's try again.

* I think I got it now lol

* Update cartoonnetwork.py

* Update cartoonnetwork.py

* Update cartoonnetwork.py

* [CartoonNetwork] Cleaned up some of the code.

* Cleaned up all of the code.

Changed auth around so you don't need to use if statements and more. :/

* Removed something I forgot to remove lol

* Changed something since title was something else.